---
title: "Lab 03 - Nobel laureates"
author: "George Nesbitt"
date: "01/28/2026"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
nobel <- read_csv("data/nobel.csv")
```

## Exercises

### Exercise 1
There are 935 observations and 26 variables in the nobel dataset
```{r glimpse of nobel}
glimpse(nobel)
```

### Exercise 2
```{r new data frame}
nobel_living <- nobel %>%
  filter(is.na(died_date),!is.na(country),gender != "org")
```
```{r glimpse of new data frame}
glimpse(nobel_living)
```


### Exercise 3
```{r}
nobel_living <- nobel_living %>%
  mutate(
    country_us = if_else(country == "USA", "USA", "Other")
  )
```
```{r}
nobel_living_science <- nobel_living %>%
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))
```
```{r}
ggplot(data=nobel_living_science, mapping=aes(y=category))+geom_bar()+facet_wrap(~country_us)
```

There were more nobel laurates that won their prizes in the US than in other countries. Specifically, economists were 
almost primarily in the United States. This supports the Buzzfeed headline. 

### Exercise 4

...

### Exercise 5

...

### Exercise 6

...
